apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-service
  template:
    metadata:
      labels:
        app: counter-service
    spec:
      containers:
        - name: counter-service
          image: 686255960187.dkr.ecr.eu-west-1.amazonaws.com/michaels/counter-service:latest
          ports:
            - containerPort: 80
