# This workflow will build a docker image running a python application and will upload the image to an ECR repository,
# and then deploy it to a kubernetes cluster

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Python CI/CD with docker build

on:
  workflow_dispatch: 
  push:
    branches: [ "master", "dev"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set next patch version
      run: echo "GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
      
    - name: Print branch name
      run: echo "$GIT_BRANCH"

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: my-docker-hub-namespace/my-docker-hub-repository

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and export to Docker
      uses: docker/build-push-action@v6
      with:
        load: true
        push: false
        file: Dockerfile
        context: .
        tags: |
          "counter-service:${{  env.GIT_BRANCH  }}"
        labels: ${{ steps.meta.outputs.labels }}
        
        
    - name: Upload artifact - src code
      uses:
        actions/upload-artifact@v4
      with: 
        name: src folder
        path: .
